/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedTransaksiIndexRouteImport } from './routes/_protected/transaksi/index'
import { Route as ProtectedTransaksiBerulangIndexRouteImport } from './routes/_protected/transaksi-berulang/index'
import { Route as ProtectedLaporanIndexRouteImport } from './routes/_protected/laporan/index'
import { Route as ProtectedKategoriIndexRouteImport } from './routes/_protected/kategori/index'
import { Route as ProtectedDompetIndexRouteImport } from './routes/_protected/dompet/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedAnggaranIndexRouteImport } from './routes/_protected/anggaran/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedTransaksiIndexRoute = ProtectedTransaksiIndexRouteImport.update({
  id: '/transaksi/',
  path: '/transaksi/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTransaksiBerulangIndexRoute =
  ProtectedTransaksiBerulangIndexRouteImport.update({
    id: '/transaksi-berulang/',
    path: '/transaksi-berulang/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLaporanIndexRoute = ProtectedLaporanIndexRouteImport.update({
  id: '/laporan/',
  path: '/laporan/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKategoriIndexRoute = ProtectedKategoriIndexRouteImport.update({
  id: '/kategori/',
  path: '/kategori/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDompetIndexRoute = ProtectedDompetIndexRouteImport.update({
  id: '/dompet/',
  path: '/dompet/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnggaranIndexRoute = ProtectedAnggaranIndexRouteImport.update({
  id: '/anggaran/',
  path: '/anggaran/',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/anggaran/': typeof ProtectedAnggaranIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/dompet/': typeof ProtectedDompetIndexRoute
  '/kategori/': typeof ProtectedKategoriIndexRoute
  '/laporan/': typeof ProtectedLaporanIndexRoute
  '/transaksi-berulang/': typeof ProtectedTransaksiBerulangIndexRoute
  '/transaksi/': typeof ProtectedTransaksiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/anggaran': typeof ProtectedAnggaranIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dompet': typeof ProtectedDompetIndexRoute
  '/kategori': typeof ProtectedKategoriIndexRoute
  '/laporan': typeof ProtectedLaporanIndexRoute
  '/transaksi-berulang': typeof ProtectedTransaksiBerulangIndexRoute
  '/transaksi': typeof ProtectedTransaksiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/anggaran/': typeof ProtectedAnggaranIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dompet/': typeof ProtectedDompetIndexRoute
  '/_protected/kategori/': typeof ProtectedKategoriIndexRoute
  '/_protected/laporan/': typeof ProtectedLaporanIndexRoute
  '/_protected/transaksi-berulang/': typeof ProtectedTransaksiBerulangIndexRoute
  '/_protected/transaksi/': typeof ProtectedTransaksiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/anggaran/'
    | '/dashboard/'
    | '/dompet/'
    | '/kategori/'
    | '/laporan/'
    | '/transaksi-berulang/'
    | '/transaksi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/anggaran'
    | '/dashboard'
    | '/dompet'
    | '/kategori'
    | '/laporan'
    | '/transaksi-berulang'
    | '/transaksi'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/unauthorized'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/anggaran/'
    | '/_protected/dashboard/'
    | '/_protected/dompet/'
    | '/_protected/kategori/'
    | '/_protected/laporan/'
    | '/_protected/transaksi-berulang/'
    | '/_protected/transaksi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/transaksi/': {
      id: '/_protected/transaksi/'
      path: '/transaksi'
      fullPath: '/transaksi/'
      preLoaderRoute: typeof ProtectedTransaksiIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/transaksi-berulang/': {
      id: '/_protected/transaksi-berulang/'
      path: '/transaksi-berulang'
      fullPath: '/transaksi-berulang/'
      preLoaderRoute: typeof ProtectedTransaksiBerulangIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/laporan/': {
      id: '/_protected/laporan/'
      path: '/laporan'
      fullPath: '/laporan/'
      preLoaderRoute: typeof ProtectedLaporanIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/kategori/': {
      id: '/_protected/kategori/'
      path: '/kategori'
      fullPath: '/kategori/'
      preLoaderRoute: typeof ProtectedKategoriIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dompet/': {
      id: '/_protected/dompet/'
      path: '/dompet'
      fullPath: '/dompet/'
      preLoaderRoute: typeof ProtectedDompetIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/anggaran/': {
      id: '/_protected/anggaran/'
      path: '/anggaran'
      fullPath: '/anggaran/'
      preLoaderRoute: typeof ProtectedAnggaranIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAnggaranIndexRoute: typeof ProtectedAnggaranIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDompetIndexRoute: typeof ProtectedDompetIndexRoute
  ProtectedKategoriIndexRoute: typeof ProtectedKategoriIndexRoute
  ProtectedLaporanIndexRoute: typeof ProtectedLaporanIndexRoute
  ProtectedTransaksiBerulangIndexRoute: typeof ProtectedTransaksiBerulangIndexRoute
  ProtectedTransaksiIndexRoute: typeof ProtectedTransaksiIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnggaranIndexRoute: ProtectedAnggaranIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDompetIndexRoute: ProtectedDompetIndexRoute,
  ProtectedKategoriIndexRoute: ProtectedKategoriIndexRoute,
  ProtectedLaporanIndexRoute: ProtectedLaporanIndexRoute,
  ProtectedTransaksiBerulangIndexRoute: ProtectedTransaksiBerulangIndexRoute,
  ProtectedTransaksiIndexRoute: ProtectedTransaksiIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
